backstop_report.backstop_report.*:
  type: config_entity
  label: Backstop Report
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string
