backstop_scenario.backstop_scenario.*:
  type: config_entity
  label: Backstop Scenario
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string

# Default value.
field.value.bs_keypress_selector:
  type: mapping
  label: Default value
  mapping:
    selector:
      type: string
      label: Selector
    keyPress:
      type: string
      label: Key Press
