<?php

/**
 * @file
 * Primary module hooks for BackstopJS module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_help().
 */
function backstop_generator_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  $path = Drupal::moduleHandler()->getModule('backstop_generator')->getPath();
  $help_file = file_get_contents($path . '/README.md');

  switch ($route_name) {
    case 'help.page.backstop_generator':
      return t($help_file);
  }
}

/**
 * Implements hook_form_alter().
 */
function backstop_generator_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if (
    $form_id == 'backstop_generator_settings' ||
    $form_id == 'backstop_report_add_form' ||
    $form_id == 'backstop_report_edit_form' ||
    $form_id == 'backstop_scenario_add_form' ||
    $form_id == 'backstop_scenario_edit_form'
  ) {
    $form['#attached']['library'][] = 'backstop_generator/backstop_forms';
  }
}
