backstop_js.settings:
  type: config_entity
  label: Backstop Settings
  mapping:
    backstop_directory:
      type: string
      label: Backstop Directory
    onBeforeScript:
      type: string
      label: onBeforeScript
    paths:
      type: string
      label: paths
    report:
      type: string
      label: report
    engine:
      type: string
      label: engine
    engineOptions:
      type: string
      label: engineOptions
    asyncCaptureLimit:
      type: integer
      label: asyncCaptureLimit
    asyncCompareLimit:
      type: integer
      label: asyncCompareLimit
    debug:
      type: boolean
      label: debug
    debugWindow:
      type: boolean
      label: debugWindow
